### ISSUE TITLE
Currently v 1.21.0 requires http-server installed in path

### ISSUE THREAD

**Issue by tomachinz** [tomachinz/AminoSee#69]
Trying to run the compiled binary results in the message below. I know why though. It is because I am trying to spawn http-server from the CLI because I do not know how to launch it from inside my app (and have it survive the main app exiting).

```
Error: spawn http-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:59:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
    at onErrorNT (internal/child_process.js:442:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:17:11
```

I think to solve this in future I will instead self-sawn AminoSee itself to run in background. For now this can be solved with:

`npm install -g http-server
`

**Comment by tomachinz** [comment]
Since version 1.27.1 no longer needs http-server installed globally. It has its own copy now.
